### ISSUE TITLE
trim whitespaces from mailaddress on login

### ISSUE THREAD

**Issue by tynsh** [fosterfarrell9/mampf#5] opened 2017-11-01 13:12 UTC
In the login dialogue should trim whitespaces in the email field automatically. Some tablets enter a whitespace automatically and it may not be clear to some users why they get the message "Please enter an email address".

Alternatively a more helpful error message would help as well.

**Comment by fosterfarrell9** [comment] 2017-11-01 16:38
That is strange, as in config/initializers/devise.rb we have

 ```
# Configure which authentication keys should have whitespace stripped.
# These keys will have whitespace before and after removed upon creating or
# modifying a user and when used to authenticate or find a user. Default is :email.
  config.strip_whitespace_keys = [:email]

```
which should prevent the behaviour mentioned in the bug report. We will look into it in the next days.

**Comment by fosterfarrell9** [comment] 2019-03-03 13:10
I could not reproduce this with several tablets. I am closing this for now, maybe we should reopen it if the problem persists.

**Closed by fosterfarrell9** 2019-03-03 13:10 UTC
Labels: bug
